global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

# define new exporters under this
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

# listen on node exporter
- job_name: node
  static_configs:
  - targets:
    # keep this as HOSTIP, the bash script will automatically replace it with the correct ip address
    - HOSTIP:9100

- job_name: push_gateway
  static_configs:
  - targets:
    - HOSTIP:9091