echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu8/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu9/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu10/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu11/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu12/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu13/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu14/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu15/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu16/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu17/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu18/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu19/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu20/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu21/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu22/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu23/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu24/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu25/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu26/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu27/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu28/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu29/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu30/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu31/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu32/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu33/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu34/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu35/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu36/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu37/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu38/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu39/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu40/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu41/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu42/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu43/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu44/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu45/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu46/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu47/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu48/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu49/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu50/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu51/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu52/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu53/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu54/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu55/cpufreq/scaling_governor
