name: changes
on: 
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      # Clone Repository
      - name: Checkout
        uses: actions/checkout@v1
      # Echo the current branch name
      - name: Echo Branch name
        run: echo ${{github.ref}}
      #
      - name: Test Branch Name
        if: github.ref != 'refs/heads/develop'
        run: |
          echo Run on refs/heads/develop not ${{github.ref}}
          exit 1
          
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"
      
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
          
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
          
      - name: Run Lint Script
        run: python style/gwclint.py ${{ steps.getfile.outputs.files }}
