name: changes
on: 
  pull_request:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      
      # Clone Repository
      - name: Checkout
        uses: actions/checkout@v1
      
      # Echo the current branch name
      - name: Echo Branch name
        run: echo ${{github.ref}}
      
      # If Branch name is not develop, exit
      - name: Test Branch Name
        if: github.ref != 'refs/heads/develop'
        run: |
          echo Run on refs/heads/develop not ${{github.ref}}
          exit 1
      
      # Get the name of the changed files. 
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"
      
      # Print the names.
      - name: echo output
        run: echo ${{ steps.getfile.outputs.files }}
        
      # Install Python.
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'

      # Run lint on user's files and writes output to file1.
      - name: RunLint on User Changes
        continue-on-error: true
        run: python style/gwclint.py ${{ steps.getfile.outputs.files }} &> file1.txt
                       
      # Clone Mater Branch.
      - name: Clone Master
        run: git clone https://github.com/sdnfv/openNetVM.git
      
      # Runs Lint on Master and writes output to 'file2'
      - name: Run Lint on Master
        continue-on-error: true
        run: |
          python style/gwclint.py openNetVM/${{ steps.getfile.outputs.files }} &> file2.txt
      
      - name : Echo User's Lint
        run: cat file1.txt
      
      - name : Echo Master's Lint
        run: cat file2.txt
      
      # Perform check for increased number of errors.
      - name: List Errors
        run: |
         echo "If Failed, refer to step 'Echo User's Lint' and 'Echo Master's Lint'. Please revise code to ensure there is not an increased number of errors compared to the master lint."
         [ "$(wc -l < file1.txt)" -eq "$(wc -l < file2.txt)" ]
